version: "3.0"

services:
  database:
    image: mysql:8
    container_name: practice_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0205
      MYSQL_USER: cooper
      MYSQL_PASSWORD: 0205
      MYSQL_DATABASE: test01_db
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net

  application:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - database
    container_name: application-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://practice_mysql:3306/test01_db
      SPRING_DATASOURCE_USERNAME: cooper
      SPRING_DATASOURCE_PASSWORD: 0205
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge